"use client";
import {useEffect,useMemo,useState} from "react";
import {AnimatePresence,motion} from "framer-motion";
import BaristaNotesCard from "../../../components/BaristaNotesCard";
import CafeReceiptExport from "../../../components/CafeReceiptExport";
import CafeChart from "../../../components/CafeChart";

type Row={date:string;value:number};type Fund={profile:{name:string;sector:string;industry:string};revenue:Row[];netIncome:Row[];eps:Row[];freeCashFlow:Row[];debt:Row[];equity:Row[];quarterly?:Record<string,Row[]>;source:string};type Quote={price:number;changePct:number;change?:number;exchange:string;marketState:string;asOf:string;source:string;points:{t:number;v:number}[]};
const latest=(r?:Row[])=>r?.[r.length-1]?.value;const growth=(r?:Row[])=>r&&r.length>1&&r[r.length-2].value?((r[r.length-1].value-r[r.length-2].value)/Math.abs(r[r.length-2].value))*100:null;
export default function StockPage({params}:{params:Promise<{ticker:string}>}){const [ticker,setTicker]=useState("RELIANCE"),[theme,setTheme]=useState<"light"|"dark">("light"),[quote,setQuote]=useState<Quote|null>(null),[fund,setFund]=useState<Fund|null>(null),[isMenuMode,setIsMenuMode]=useState("journal");
 useEffect(()=>{const s=localStorage.getItem("stocklens-theme");if(s==="dark")setTheme("dark");params.then(p=>setTicker(decodeURIComponent(p.ticker).toUpperCase()))},[params]);
 useEffect(()=>{if(!ticker)return;fetch("/api/quote?ticker="+encodeURIComponent(ticker)+"&range=1y",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setQuote).catch(()=>{});fetch("/api/fundamentals?ticker="+encodeURIComponent(ticker),{cache:"no-store"}).then(r=>r.ok?r.json():null).then(setFund).catch(()=>{})},[ticker]);
 const company=fund?.profile?.name||ticker,price=quote?.price||0,change=quote?.changePct||0,eps=latest(fund?.eps),pe=eps&&eps>0?price/eps:null,revGrowth=growth(fund?.revenue),points=quote?.points||[];
 return <div className={"study-app "+theme}><header className="study-nav"><a className="cafe-brand" href="/">stocklens☕</a><a href="/">← back to the cafe</a><button className="theme-button" onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label="Toggle theme">{theme==="light"?"☾":"☀"}</button><div className="menu-toggle"><button className={isMenuMode==="journal"?"active":""} onClick={()=>setIsMenuMode("journal")}>Journal</button><button className={isMenuMode==="ledger"?"active":""} onClick={()=>setIsMenuMode("ledger")}>Ledger</button></div></header><main className="study-main"><div className="study-heading"><div><span className="stamp">{quote?.exchange||"MARKET"} · {ticker}</span><h1>{company}</h1><p>{fund?.profile?.sector||"Market security"}{fund?.profile?.industry?" · "+fund.profile.industry:""}</p></div><div className="quote-note"><strong>₹{price?price.toLocaleString("en-IN",{maximumFractionDigits:2}):"—"}</strong><span className={change>=0?"matcha":"berry"}>{quote?(change>=0?"+":"")+change.toFixed(2)+"%":"quote pending"}</span><small>{quote?.source||"No quote response"} · {quote?.asOf?new Date(quote.asOf).toLocaleString("en-IN"):"—"}</small></div></div>
 <AnimatePresence mode="wait">
 {isMenuMode==="journal"?<motion.div key="journal" className="journal-desk" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{type:"spring",stiffness:120,damping:20}}>
  <div className="desk-column"><BaristaNotesCard company={company} price={price} change={change} pe={pe} growth={revGrowth}/><div className="notebook-panel"><div className="notebook-title"><div><span>PRICE TRAIL · MOLESKINE</span><small>FOLLOW THE LINE</small></div><small>{points.length>1?`${points.length} returned points`:"Awaiting history"}</small></div><CafeChart points={points} positive={change>=0}/></div></div><CafeReceiptExport company={company} ticker={ticker} price={price} pe={pe}/>
 </motion.div>:<motion.div key="ledger" className="ledger-book" initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.01}} transition={{type:"spring",stiffness:120,damping:20}}><div className="ledger-cover"><span>STOCKLENS</span><strong>INVESTOR'S LEDGER</strong><small>{ticker} · {new Date().getFullYear()}</small></div><div className="ledger-page"><div className="ledger-title"><span>FINANCIAL INVENTORY</span><b>SOURCE: {fund?.source||"PENDING"}</b></div><table><thead><tr><th>METRIC</th><th>LATEST</th><th>PREVIOUS</th><th>CHANGE</th></tr></thead><tbody>{[["Revenue",fund?.revenue],["Net income",fund?.netIncome],["EPS",fund?.eps],["Free cash flow",fund?.freeCashFlow],["Debt",fund?.debt],["Equity",fund?.equity]].map(([label,rows])=>{const r=rows as Row[]|undefined,a=latest(r),prev=r&&r.length>1?r[r.length-2].value:null,g=r&&r.length>1&&prev?((a!-prev)/Math.abs(prev))*100:null;return <tr key={label as string}><td>{label as string}</td><td>{a==null?"—":a.toLocaleString("en-IN",{maximumFractionDigits:2})}</td><td>{prev==null?"—":prev.toLocaleString("en-IN",{maximumFractionDigits:2})}</td><td className={g!=null&&g>=0?"matcha":"berry"}>{g==null?"—":(g>=0?"+":"")+g.toFixed(1)+"%"}</td></tr>})}</tbody></table><div className="ledger-foot">Ruled like a notebook. Sourced like a ledger. Interpretations remain separate from reported figures.</div></div></motion.div>}
 </AnimatePresence></main></div>
}