import { NextResponse } from "next/server";

const symbols:Record<string,string>={
  RELIANCE:"RELIANCE.NS",TCS:"TCS.NS",HDFCBANK:"HDFCBANK.NS",INFY:"INFY.NS",ICICIBANK:"ICICIBANK.NS",SBIN:"SBIN.NS",BHARTIARTL:"BHARTIARTL.NS",ITC:"ITC.NS",LT:"LT.NS",AXISBANK:"AXISBANK.NS",KOTAKBANK:"KOTAKBANK.NS",HINDUNILVR:"HINDUNILVR.NS",MARUTI:"MARUTI.NS",SUNPHARMA:"SUNPHARMA.NS",TATAMOTORS:"TATAMOTORS.NS",TATASTEEL:"TATASTEEL.NS",WIPRO:"WIPRO.NS",HCLTECH:"HCLTECH.NS",ASIANPAINT:"ASIANPAINT.NS",ADANIENT:"ADANIENT.NS"
};
const groups={revenue:["annualTotalRevenue"],netIncome:["annualNetIncome"],eps:["annualDilutedEPS"],freeCashFlow:["annualFreeCashFlow"],operatingCashFlow:["annualOperatingCashFlow"],debt:["annualTotalDebt"],equity:["annualStockholdersEquity"],cash:["annualCashCashEquivalentsAndShortTermInvestments"]};
type Row={date:string;value:number};
function rows(result:any,key:string):Row[]{const r=result?.timeseries?.result?.find((x:any)=>x.meta?.symbol===key)||result?.timeseries?.result?.find((x:any)=>Object.keys(x).some(k=>k.toLowerCase().includes(key.toLowerCase().replace("annual",""))));return (r?.timestamp||[]).map((t:number,i:number)=>({date:new Date(t*1000).toISOString().slice(0,10),value:Number(r[key]?.[i]?.raw??r[key]?.[i]??NaN)})).filter((x:Row)=>Number.isFinite(x.value)).sort((a:Row,b:Row)=>a.date.localeCompare(b.date)).slice(-5)}
async function getSeries(symbol:string,types:string[]){for(const host of ["query2.finance.yahoo.com","query1.finance.yahoo.com"]){const u=new URL(`https://${host}/ws/fundamentals-timeseries/v1/finance/timeseries/${encodeURIComponent(symbol)}`);u.searchParams.set("symbol",symbol);u.searchParams.set("type",types.join(","));u.searchParams.set("period1","1483142400");u.searchParams.set("period2",String(Math.floor(Date.now()/1000)));const r=await fetch(u,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 StockLens/1.0"}});if(r.ok)return r.json()}throw new Error("Fundamentals provider unavailable")}
export async function GET(request:Request){const ticker=new URL(request.url).searchParams.get("ticker")?.toUpperCase()||"";const symbol=symbols[ticker]||(ticker.endsWith(".NS")?ticker:/^[A-Z0-9&-]{1,30}$/.test(ticker)?`${ticker}.NS`:null);if(!symbol)return NextResponse.json({error:"Unsupported ticker"},{status:400});try{const data=await getSeries(symbol,Object.values(groups).flat());const out:any={ticker,symbol,currency:"INR",source:"Yahoo Finance fundamentals time series",updatedAt:new Date().toISOString(),profile:{name:ticker,sector:"",industry:"",description:""},revenue:[],netIncome:[],eps:[],freeCashFlow:[],operatingCashFlow:[],debt:[],equity:[],cash:[]};for(const [name,types] of Object.entries(groups))out[name]=rows(data,types[0]);return NextResponse.json(out,{headers:{"Cache-Control":"s-maxage=900, stale-while-revalidate=3600"}})}catch(error){return NextResponse.json({error:"Fundamentals unavailable",detail:error instanceof Error?error.message:"Unknown provider error"},{status:502})}}
