"use client";

import {useEffect,useMemo,useRef,useState} from "react";

const stocks=[{t:"RELIANCE",n:"Reliance Industries"},{t:"TCS",n:"Tata Consultancy Services"},{t:"HDFCBANK",n:"HDFC Bank"},{t:"INFY",n:"Infosys"}];
const market=[{t:"NIFTY",n:"NIFTY 50"},{t:"SENSEX",n:"SENSEX"},{t:"BANKNIFTY",n:"BANK NIFTY"}];
const periods=["1D","1W","1M","1Y","5Y"];
const fallbackQuotes:Record<string,{price:number,changePct:number}>={
 RELIANCE:{price:1420.8,changePct:1.84},TCS:{price:3918.4,changePct:-.42},HDFCBANK:{price:1012.6,changePct:.71},INFY:{price:1521.25,changePct:1.12},
 NIFTY:{price:25418.9,changePct:.63},SENSEX:{price:83217.1,changePct:.51},BANKNIFTY:{price:56841.3,changePct:.78}
};
type Quote={ticker:string;price:number;changePct:number;currency:string;exchange:string;marketState:string;asOf:string;points:{t:number;v:number}[];source:string};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
const pct=(n:number)=>(n>=0?"+":"")+n.toFixed(2)+"%";

export default function Home(){
 const [dark,setDark]=useState(false),[q,setQ]=useState(""),[active,setActive]=useState("Overview"),[watch,setWatch]=useState(false),[period,setPeriod]=useState("1D"),[selected,setSelected]=useState("RELIANCE");
 const [quotes,setQuotes]=useState<Record<string,Quote>>({}),[loading,setLoading]=useState(false),[live,setLive]=useState(false),[chartLoading,setChartLoading]=useState(false);
 const searchRef=useRef<HTMLInputElement>(null);
 const filtered=stocks.filter(s=>(s.t+" "+s.n).toLowerCase().includes(q.toLowerCase()));
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[]);
 useEffect(()=>{let cancelled=false;setLoading(true);const tickers=stocks.map(s=>s.t).concat(market.map(s=>s.t));
 Promise.all(tickers.map(async t=>{try{const r=await fetch("/api/quote?ticker="+t,{cache:"no-store"});if(!r.ok)throw new Error();return [t,await r.json() as Quote] as const}catch{return null}})).then(rows=>{if(cancelled)return;const next:Record<string,Quote>={};rows.forEach(row=>{if(row&&row[1]?.price)next[row[0]]=row[1]});setQuotes(next);setLive(Object.keys(next).length>0)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
 const choose=(ticker:string)=>{setSelected(ticker);setQ("");setPeriod("1D");document.getElementById("analysis")?.scrollIntoView({behavior:"smooth",block:"start"})};
 const rangeMap:Record<string,string>={"1D":"1d","1W":"1w","1M":"1mo","1Y":"1y","5Y":"5y"};
 useEffect(()=>{let cancelled=false; if(period==="1D") return; setChartLoading(true); fetch("/api/quote?ticker="+selected+"&range="+rangeMap[period],{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{if(cancelled||!data?.price)return; setQuotes(prev=>({...prev,[selected]:data}));}).catch(()=>{}).finally(()=>{if(!cancelled)setChartLoading(false)}); return()=>{cancelled=true}},[selected,period]);
 const current=quotes[selected], fallback=fallbackQuotes[selected], price=current?.price??fallback?.price??0, changePct=current?.changePct??fallback?.changePct??0;
 const currentName=stocks.find(s=>s.t===selected)?.n??selected;
 const chartPoints=current?.points?.length?current.points.map(p=>p.v):[];
 const chartPath=useMemo(()=>{const values=chartPoints;if(values.length<2)return "M0 190 C120 155 190 175 300 130 S520 140 650 90 S800 75 900 50";const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>(i?"L":"M")+(i/(values.length-1))*900+" "+(235-((v-min)/range)*190)).join(" ")},[chartPoints]);
 const insights=active==="Overview"?[["REVENUE GROWTH","+12.8%","Illustrative lens"],["ROCE","11.9%","Connect fundamentals"],["NET DEBT","₹1.18T","Connect financials"],["VALUATION","1.08×","Historical context"]]:active==="Financials"?[[ "REVENUE","—","Data connector needed"],["NET PROFIT","—","Data connector needed"],["EPS","—","Data connector needed"],["CASH FLOW","—","Data connector needed"]]:active==="Valuation"?[[ "P/E","—","Data connector needed"],["P/B","—","Data connector needed"],["EV/EBITDA","—","Data connector needed"],["5Y MEDIAN","—","Historical data needed"]]:[[ "LEVERAGE","—","Data connector needed"],["MARGIN","—","Data connector needed"],["CYCLICALITY","—","Sector model needed"],["KEY WATCH","—","Research model needed"]];

 return <main className={dark?"dark":""}>
 <header className="nav glass"><a className="brand" href="#top" aria-label="StockLens home"><span className="mark">S</span><span>stock<span>lens</span></span></a><nav aria-label="Primary"><a href="#market">Markets</a><a href="#discover">Discover</a><a href="#analysis">Analysis</a><a className="active" href="#analysis">Lens</a></nav><div className="nav-actions"><button className="icon" aria-label={dark?"Switch to light mode":"Switch to dark mode"} onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="profile" aria-label="Profile">HB</button></div></header>
 <section id="top" className="hero"><div className="eyebrow">MARKET INTELLIGENCE, WITHOUT THE NOISE</div><h1>SEE THE MARKET<br/><em>CLEARLY.</em></h1><p>Search a stock. Understand the business. See what actually changed.</p><div className="search glass"><span aria-hidden="true">⌕</span><input ref={searchRef} value={q} onChange={e=>setQ(e.target.value)} aria-label="Search stocks, companies or ETFs" placeholder="Search stocks, companies or ETFs…" /><kbd>⌘ K</kbd></div>{q&&<div className="results glass">{filtered.length?filtered.map(s=><button key={s.t} onClick={()=>choose(s.t)}><b>{s.t}</b><span>{s.n}</span><strong>{quotes[s.t]?money(quotes[s.t].price):money(fallbackQuotes[s.t].price)} <small>{pct(quotes[s.t]?.changePct??fallbackQuotes[s.t].changePct)}</small></strong></button>):<p>No matching stock found. Try Reliance, TCS, HDFC or Infosys.</p>}</div>}</section>
 <section id="market" className="section"><div className="section-head"><div><div className="eyebrow">TODAY</div><h2>Market pulse</h2></div><span className={live?"live live-on":"live"}>{loading?"● Updating…":live?"● Live quote feed":"● Demo fallback"}</span></div><div className="market-grid">{market.map(x=>{const f=fallbackQuotes[x.t],c=quotes[x.t];return <button className="market glass" key={x.t} onClick={()=>choose(x.t)}><span>{x.n}</span><b>{c?money(c.price):money(f.price)}</b><small>{pct(c?.changePct??f.changePct)}</small><div className="spark">{[18,22,19,27,24,32,29,38,35,44].map((h,i)=><i style={{height:h}} key={i}/>)}</div></button>})}</div><p className="demo-note">{live?"Quotes are fetched at page load from the connected market feed.":"Live market feed is unavailable right now; illustrative fallback values are shown."}</p></section>
 <section id="analysis" className="analysis glass"><div className="analysis-top"><div><div className="eyebrow">{live?"LIVE QUOTE":"FALLBACK QUOTE"} / STOCKLENS</div><h2>{currentName}</h2><div className="ticker">{selected+" · NSE"+(current?.marketState?" · "+current.marketState:"")}</div></div><button className={watch?"watch on":"watch"} aria-pressed={watch} onClick={()=>setWatch(!watch)}>{watch?"★ Watching":"☆ Watchlist"}</button></div><div className="price-row"><div><strong>{money(price)}</strong><span className={changePct>=0?"gain":"loss"}>{pct(changePct)}</span></div><div className="periods" aria-label="Chart period">{periods.map(p=><button className={period===p?"sel":""} aria-pressed={period===p} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div>{chartLoading&&<span className="chart-status">Updating chart…</span>}</div><div className="chart" role="img" aria-label={selected+" "+period+" price chart"}><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d={chartPath} fill="none" stroke="currentColor" strokeWidth="3"/><path d={chartPath+" L900 260 L0 260Z"} fill="url(#fill)"/></svg></div><div className="tabs" role="tablist">{["Overview","Financials","Valuation","Risks"].map(t=><button role="tab" aria-selected={active===t} className={active===t?"tab active":"tab"} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div><div className="insights">{insights.map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div>{current&&<div className="quote-meta">Source: {current.source} · Updated {new Date(current.asOf).toLocaleString("en-IN")}</div>}</section>
 <section id="discover" className="lens glass"><div><div className="eyebrow">WHAT IS STOCKLENS SEEING?</div><h2>The numbers, <em>interpreted.</em></h2><p>StockLens separates live market data from analysis so you can see what is measured, what is inferred, and what still needs a deeper data connection.</p></div><div className="lens-points"><div><span>01</span><b>Live market layer</b><small>Current quotes are fetched independently from the analysis model.</small></div><div><span>02</span><b>Financial layer</b><small>Fundamentals require a dedicated financial-data connector.</small></div><div><span>03</span><b>Lens layer</b><small>AI interpretation can sit on top once those datasets are connected.</small></div></div></section>
 <footer><span>stocklens</span><span>{live?"Live quotes enabled · Financial analysis connector pending":"Demo fallback · Live provider unavailable"}</span></footer>
 </main>;
}