"use client";
import {useState} from "react";
const stocks=[["RELIANCE","Reliance Industries","₹1,420.80","+1.84%"],["TCS","Tata Consultancy Services","₹3,918.40","-0.42%"],["HDFCBANK","HDFC Bank","₹1,012.60","+0.71%"],["INFY","Infosys","₹1,521.25","+1.12%"]];
export default function Home(){const [dark,setDark]=useState(false);const [q,setQ]=useState("");const [active,setActive]=useState("Overview");const [watch,setWatch]=useState(false);const filtered=stocks.filter(s=>s.join(" ").toLowerCase().includes(q.toLowerCase()));return <main className={dark?"dark":""}>
<header className="nav glass"><div className="brand"><span className="mark">S</span><span>stock<span>lens</span></span></div><nav><a>Markets</a><a>Discover</a><a>Portfolio</a><a className="active">Lens</a></nav><div className="nav-actions"><button className="icon" onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="profile">HB</button></div></header>
<section className="hero"><div className="eyebrow">MARKET INTELLIGENCE, WITHOUT THE NOISE</div><h1>SEE THE MARKET<br/><em>CLEARLY.</em></h1><p>Search a stock. Understand the business. See what actually changed.</p><div className="search glass"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search stocks, companies or ETFs…" /><kbd>⌘ K</kbd></div>{q&&<div className="results glass">{filtered.length?filtered.map(s=><button key={s[0]} onClick={()=>setQ(s[0])}><b>{s[0]}</b><span>{s[1]}</span><strong>{s[2]}</strong></button>):<p>No matching stock found.</p>}</div>}</section>
<section className="section"><div className="section-head"><div><div className="eyebrow">TODAY</div><h2>Market pulse</h2></div><span className="live">● Market snapshot</span></div><div className="market-grid">{[["NIFTY 50","25,418.90","+0.63%"],["SENSEX","83,217.10","+0.51%"],["BANK NIFTY","56,841.30","+0.78%"]].map(x=><div className="market glass" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small><div className="spark">{[18,22,19,27,24,32,29,38,35,44].map((h,i)=><i style={{height:h}} key={i}/>)}</div></div>)}</div></section>
<section className="analysis glass"><div className="analysis-top"><div><div className="eyebrow">STOCKLENS / DEMO ANALYSIS</div><h2>Reliance Industries</h2><div className="ticker">RELIANCE · NSE</div></div><button className={watch?"watch on":"watch"} onClick={()=>setWatch(!watch)}>{watch?"★ Watching":"☆ Watchlist"}</button></div><div className="price-row"><div><strong>₹1,420.80</strong><span className="gain">+25.65 · +1.84%</span></div><div className="periods">{["1D","1W","1M","1Y","5Y"].map(p=><button className={p==="1Y"?"sel":""} key={p}>{p}</button>)}</div></div><div className="chart"><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d="M0 210 C80 180 95 195 150 160 S245 175 300 125 S390 155 450 105 S540 135 600 80 S690 120 750 65 S840 90 900 38 L900 260 L0 260Z" fill="url(#fill)"/><path d="M0 210 C80 180 95 195 150 160 S245 175 300 125 S390 155 450 105 S540 135 600 80 S690 120 750 65 S840 90 900 38" fill="none" stroke="currentColor" strokeWidth="3"/></svg></div><div className="tabs">{["Overview","Financials","Valuation","Risks"].map(t=><button className={active===t?"tab active": "tab"} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div><div className="insights"><div><span>REVENUE GROWTH</span><b>+12.8%</b><small>Expanding steadily</small></div><div><span>ROCE</span><b>11.9%</b><small>Stable over 3Y</small></div><div><span>NET DEBT</span><b>₹1.18T</b><small>Watch leverage</small></div><div><span>VALUATION</span><b>1.08×</b><small>vs. 5Y median</small></div></div></section>
<section className="lens glass"><div><div className="eyebrow">WHAT IS STOCKLENS SEEING?</div><h2>The numbers, <em>interpreted.</em></h2><p>Instead of throwing ratios at you, StockLens connects growth, profitability, valuation and risk into a clearer picture.</p></div><div className="lens-points"><div><span>01</span><b>Business quality</b><small>Is the underlying business getting stronger?</small></div><div><span>02</span><b>Financial strength</b><small>Can the balance sheet support growth?</small></div><div><span>03</span><b>Valuation context</b><small>What are you paying versus history?</small></div></div></section>
<footer><span>stocklens</span><span>Demo data · Connect a market-data provider for live prices</span></footer></main>}