"use client";
import {useEffect,useRef,useState} from "react";
const stocks=[{t:"RELIANCE",n:"Reliance Industries",p:"₹1,420.80",c:"+1.84%"},{t:"TCS",n:"Tata Consultancy Services",p:"₹3,918.40",c:"-0.42%"},{t:"HDFCBANK",n:"HDFC Bank",p:"₹1,012.60",c:"+0.71%"},{t:"INFY",n:"Infosys",p:"₹1,521.25",c:"+1.12%"}];
const market=[{n:"NIFTY 50",v:"25,418.90",c:"+0.63%"},{n:"SENSEX",v:"83,217.10",c:"+0.51%"},{n:"BANK NIFTY",v:"56,841.30",c:"+0.78%"}];
const periods=["1D","1W","1M","1Y","5Y"];
const tabData={Overview:[["REVENUE GROWTH","+12.8%","Expanding steadily"],["ROCE","11.9%","Stable over 3Y"],["NET DEBT","₹1.18T","Watch leverage"],["VALUATION","1.08×","vs. 5Y median"]],Financials:[["REVENUE","₹1.00T","Latest period"],["NET PROFIT","₹18.2K Cr","Latest period"],["EPS","₹133.4","Latest period"],["CASH FLOW","Positive","Operating"]],Valuation:[["P/E","24.6×","Current"],["P/B","2.2×","Current"],["EV/EBITDA","13.8×","Current"],["5Y MEDIAN","1.08×","Relative context"]],Risks:[["LEVERAGE","₹1.18T","Net debt"],["MARGIN","14.2%","Monitor trend"],["CYCLICALITY","Medium","Sector exposure"],["KEY WATCH","Capex","Execution"]]};
const paths={"1D":"M0 210 C80 180 95 195 150 160 S245 175 300 125 S390 155 450 105 S540 135 600 80 S690 120 750 65 S840 90 900 38","1W":"M0 190 C80 210 120 155 180 175 S280 125 340 150 S430 110 500 120 S620 75 700 100 S820 45 900 70","1M":"M0 220 C80 190 120 200 180 145 S270 170 330 115 S430 145 500 95 S600 125 680 75 S800 105 900 48","1Y":"M0 210 C80 180 95 195 150 160 S245 175 300 125 S390 155 450 105 S540 135 600 80 S690 120 750 65 S840 90 900 38","5Y":"M0 230 C80 215 125 180 190 195 S280 135 350 155 S440 95 520 125 S610 70 690 90 S790 45 900 30"};
export default function Home(){
 const [dark,setDark]=useState(false),[q,setQ]=useState(""),[active,setActive]=useState("Overview"),[watch,setWatch]=useState(false),[period,setPeriod]=useState("1Y"),[selected,setSelected]=useState("RELIANCE");
 const searchRef=useRef<HTMLInputElement>(null);
 const filtered=stocks.filter(s=>(s.t+" "+s.n).toLowerCase().includes(q.toLowerCase()));
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",f);return()=>window.removeEventListener("keydown",f)},[]);
 const choose=(ticker:string)=>{setSelected(ticker);setQ("");document.getElementById("analysis")?.scrollIntoView({behavior:"smooth",block:"start"})};
 const current=stocks.find(s=>s.t===selected)??stocks[0];
 return <main className={dark?"dark":""}>
  <header className="nav glass"><a className="brand" href="#top" aria-label="StockLens home"><span className="mark">S</span><span>stock<span>lens</span></span></a><nav aria-label="Primary"><a href="#market">Markets</a><a href="#discover">Discover</a><a href="#analysis">Portfolio</a><a className="active" href="#analysis">Lens</a></nav><div className="nav-actions"><button className="icon" aria-label={dark?"Switch to light mode":"Switch to dark mode"} onClick={()=>setDark(!dark)}>{dark?"☀":"◐"}</button><button className="profile" aria-label="Profile">HB</button></div></header>
  <section id="top" className="hero"><div className="eyebrow">MARKET INTELLIGENCE, WITHOUT THE NOISE</div><h1>SEE THE MARKET<br/><em>CLEARLY.</em></h1><p>Search a stock. Understand the business. See what actually changed.</p><div className="search glass"><span aria-hidden="true">⌕</span><input ref={searchRef} value={q} onChange={e=>setQ(e.target.value)} aria-label="Search stocks, companies or ETFs" placeholder="Search stocks, companies or ETFs…" /><kbd>⌘ K</kbd></div>{q&&<div className="results glass">{filtered.length?filtered.map(s=><button key={s.t} onClick={()=>choose(s.t)}><b>{s.t}</b><span>{s.n}</span><strong>{s.p} <small>{s.c}</small></strong></button>):<p>No matching stock found. Try Reliance, TCS, HDFC or Infosys.</p>}</div>}</section>
  <section id="market" className="section"><div className="section-head"><div><div className="eyebrow">TODAY</div><h2>Market pulse</h2></div><span className="live">● Demo snapshot</span></div><div className="market-grid">{market.map(x=><div className="market glass" key={x.n}><span>{x.n}</span><b>{x.v}</b><small>{x.c}</small><div className="spark">{[18,22,19,27,24,32,29,38,35,44].map((h,i)=><i style={{height:h}} key={i}/>)}</div></div>)}</div><p className="demo-note">Illustrative data only. Live market prices require a connected market-data provider.</p></section>
  <section id="analysis" className="analysis glass"><div className="analysis-top"><div><div className="eyebrow">STOCKLENS / DEMO ANALYSIS</div><h2>{current.n}</h2><div className="ticker">{current.t} · NSE</div></div><button className={watch?"watch on":"watch"} aria-pressed={watch} onClick={()=>setWatch(!watch)}>{watch?"★ Watching":"☆ Watchlist"}</button></div><div className="price-row"><div><strong>{current.p}</strong><span className="gain">{current.c}</span></div><div className="periods" aria-label="Chart period">{periods.map(p=><button className={period===p?"sel":""} aria-pressed={period===p} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div></div><div className="chart" role="img" aria-label={"Illustrative "+period+" price chart"}><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity=".22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path d={paths[period as keyof typeof paths]} fill="none" stroke="currentColor" strokeWidth="3"/><path d={paths[period as keyof typeof paths]+" L900 260 L0 260Z"} fill="url(#fill)"/></svg></div><div className="tabs" role="tablist">{Object.keys(tabData).map(t=><button role="tab" aria-selected={active===t} className={active===t?"tab active":"tab"} onClick={()=>setActive(t as keyof typeof tabData)} key={t}>{t}</button>)}</div><div className="insights">{tabData[active as keyof typeof tabData].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></section>
  <section id="discover" className="lens glass"><div><div className="eyebrow">WHAT IS STOCKLENS SEEING?</div><h2>The numbers, <em>interpreted.</em></h2><p>Instead of throwing ratios at you, StockLens connects growth, profitability, valuation and risk into a clearer picture.</p></div><div className="lens-points"><div><span>01</span><b>Business quality</b><small>Is the underlying business getting stronger?</small></div><div><span>02</span><b>Financial strength</b><small>Can the balance sheet support growth?</small></div><div><span>03</span><b>Valuation context</b><small>What are you paying versus history?</small></div></div></section>
  <footer><span>stocklens</span><span>Demo data · No live market feed connected</span></footer>
 </main>
}